#!/bin/bash

/usr/local/bin/aws configure set aws_access_key_id __AWS_AK__
/usr/local/bin/aws configure set aws_secret_access_key __AWS_SK__
/usr/local/bin/aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"tag:Project","Values":["Devopsjump"]}]' --parameters '{"commands":["ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/ec2-user/ssh-key.pem ec2-user@__PRIVATE_IP_1__ \"aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 961106375848.dkr.ecr.sa-east-1.amazonaws.com; docker pull 961106375848.dkr.ecr.sa-east-1.amazonaws.com/__DOCKER_REPOSITORY_NAME__:__BRANCH_NAME__-__TAG__; docker stop __DOCKER_REPOSITORY_NAME__ || true && docker rm __DOCKER_REPOSITORY_NAME__ || true; docker run -e PORT=__PORT__ -p 80:__PORT__ --name __DOCKER_REPOSITORY_NAME__ -d 961106375848.dkr.ecr.sa-east-1.amazonaws.com/__DOCKER_REPOSITORY_NAME__:__BRANCH_NAME__-__TAG__\""],"workingDirectory":[""],"executionTimeout":["3600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region sa-east-1
/usr/local/bin/aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"tag:Project","Values":["Devopsjump"]}]' --parameters '{"commands":["ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /home/ec2-user/ssh-key.pem ec2-user@__PRIVATE_IP_2__ \"aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 961106375848.dkr.ecr.sa-east-1.amazonaws.com; docker pull 961106375848.dkr.ecr.sa-east-1.amazonaws.com/__DOCKER_REPOSITORY_NAME__:__BRANCH_NAME__-__TAG__; docker stop __DOCKER_REPOSITORY_NAME__ || true && docker rm __DOCKER_REPOSITORY_NAME__ || true; docker run -e PORT=__PORT__ -p 80:__PORT__ --name __DOCKER_REPOSITORY_NAME__ -d 961106375848.dkr.ecr.sa-east-1.amazonaws.com/__DOCKER_REPOSITORY_NAME__:__BRANCH_NAME__-__TAG__\""],"workingDirectory":[""],"executionTimeout":["3600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --region sa-east-1

/usr/local/bin/aws elbv2 deregister-targets --target-group-arn __TARGET_GROUP_ARN__ --targets Id=__INSTANCE_ID_1A__ --region sa-east-1
/usr/local/bin/aws elbv2 deregister-targets --target-group-arn __TARGET_GROUP_ARN__ --targets Id=__INSTANCE_ID_2C__ --region sa-east-1

/usr/local/bin/aws elbv2 register-targets --target-group-arn __TARGET_GROUP_ARN__ --targets Id=__INSTANCE_ID_1A__,Port=__PORT__ Id=__INSTANCE_ID_2C__,Port=__PORT__ --region sa-east-1